server:
    port: 9091

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://arjuna.db.elephantsql.com:5432/rtwauanu?useSSL=false
    username: rtwauanu
    password: {{secrets.postgrespwd}}