name: Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run docker-build with tag
      run: ./docker-build sudipbhandari/springboot-docker-app:$GITHUB_SHA
    - name: list docker images
      run: docker image ls
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: 'docker.io'
        username: '{{secrets.DOCKER_HUB_USERNAME}}'
        password: '{{secrets.DOCKER_HUB_PASSWORD}}'
    - name : docker push
      run: docker push sudipbhandari/springboot-docker-app:$GITHUB_SHA 
    - name: clean up
      run: rm ~/.docker/config.json
    
