name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run docker-build
      run: ./docker-build springboot-docker-app:$GITHUB_SHA
    - name: tag docker image
      run: docker tag springboot-docker-app:$GITHUB_SHA {{secrets.DOCKER_HUB_USERNAME}}/springboot-docker-app:$GITHUB_SHA
    - name: login to docker
      run: docker login -u={{secrets.DOCKER_HUB_USERNAME}} -p={{secrets.DOCKER_HUB_PASSWORD}}
    - name : docker push
      run: docker push {{secrets.DOCKER_HUB_USERNAME}}/springboot-docker-app:$GITHUB_SHA 
    
