name: Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run docker-build
      run: ./docker-build springboot-docker-app:$GITHUB_SHA
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        login-server: 'index.docker.io'
        username: '{{secrets.DOCKER_HUB_USERNAME}}'
        password: '{{secrets.DOCKER_HUB_PASSWORD}}'
    - name: tag docker image
      run: docker tag springboot-docker-app:$GITHUB_SHA sudipbhandari/springboot-docker-app:$GITHUB_SHA
    - name : docker push
      run: docker push docker.io/sudipbhandari/springboot-docker-app:$GITHUB_SHA 
    
